
# Map the URL path to the CGI script
ScriptAlias /habits/user1 "/srv/programs/habits_web/flask_cgi_backend.exec.py"
SetEnv HABITS_WEB_DB_PATH "/srv/config/data/habits_user1.db"

# second URL path and second DB:
#ScriptAlias /habits/user2 "/srv/programs/habits_web/flask_cgi_backend.exec.py"
#SetEnv HABITS_WEB_DB_PATH "/srv/config/data/habits_user2.db"

# Provide permissions and enable CGI execution for the CGI script directory
<Directory /srv/programs/habits_web>
  Options +FollowSymlinks +ExecCGI
  AllowOverride All
  AddHandler cgi-script .py
  Require all granted
  DirectoryIndex flask_cgi_backend.exec.py
</Directory>

# Logging configuration for errors for the URL alias
ErrorLog /srv/config/data/apache_habits_error.log
# ErrorLog ${APACHE_LOG_DIR}/habits_error.log

CustomLog ${APACHE_LOG_DIR}/access.log combined

