
# Map the URL path to the CGI script
ScriptAlias /habits/user1 "/srv/programs/habits_web/flask_cgi_backend.exec.py"

ScriptAlias /habits/user2 "/srv/programs/habits_web/flask_cgi_backend.exec.py"

# set DB path:
SetEnvIf Request_URI "^/habits/user1"    HABITS_WEB_DB_PATH=/srv/config/data/user1.db
SetEnvIf Request_URI "^/habits/user2"    HABITS_WEB_DB_PATH=/srv/config/data/user2.db

# Provide permissions and enable CGI execution for the CGI script directory
<Directory /srv/programs/habits_web>
  Options +FollowSymlinks +ExecCGI
  AllowOverride All
  AddHandler cgi-script .py
  Require all granted
  DirectoryIndex flask_cgi_backend.exec.py
</Directory>

# Logging configuration for errors for the /habits alias
ErrorLog /srv/config/data/apache_habits_error.log
# ErrorLog ${APACHE_LOG_DIR}/habits_error.log

CustomLog ${APACHE_LOG_DIR}/access.log combined

